# The aim of this file is to preprocess the raw data from the csv file.

## First we install necessary imports

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as mlpt
import shutil
import os

## load data

In [4]:
listing_data = pd.read_csv('raw_data/suumo_out/listings.csv')
images_data = pd.read_csv('raw_data/suumo_out/images.csv')

# EDA / cleaning
- remove the lisitings with less than 5 images and remove images from images.csv

In [18]:
listing_data

,source,source_id,url,price_man_yen,layout,area_sqm,year_built,floor_number,floors_total,address,nearest_station,walk_minutes,interior_image_count
0,suumo,20037131,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,2980,2LDK,NaN,2008,1,6,千葉県市川市宮久保３,京成八幡駅,20.0,0
1,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,3799,3LDK,NaN,2000,3,6,千葉県市川市広尾１-10-10,南行徳駅,17.0,13
2,suumo,20143796,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,3799,3LDK,NaN,2000,3,6,千葉県市川市広尾１,南行徳駅,17.0,14
3,suumo,78933829,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,2688,4LDK,NaN,1974,4,5,千葉県市川市高谷２-7-7,原木中山駅,8.0,13
4,suumo,79079065,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,2480,2LDK,NaN,1975,4,6,千葉県市川市宝２,行徳駅,17.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,suumo,20340216,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,2400,3LDK,NaN,1991,7,10,東京都足立区小台１,足立小台駅,8.0,12
97,suumo,20340904,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,4380,2LDK,NaN,1985,7,8,東京都足立区東和５,北綾瀬駅,9.0,26
98,suumo,20341785,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,3980,3LDK,NaN,1982,11,12,東京都足立区梅田７,梅島駅,6.0,40
99,suumo,20344541,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,2680,1DK,NaN,1989,2,3,東京都足立区綾瀬６,綾瀬駅,14.0,38
100,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,2380,2LDK,NaN,1974,3,8,東京都足立区梅田７-22-9,梅島駅,7.0,39

In [17]:
images_data

,source,source_id,listing_url,image_url,image_tag,image_path,image_sha256
0,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,https://img01.suumo.com/jj/resizeImage?src=gaz...,kitchen,suumo_images/20119720/20119720_df8db223a09d1f4...,c93f3b913205421242f7dac495beb62842929f3ae6f22c...
1,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,https://img01.suumo.com/jj/resizeImage?src=gaz...,kitchen,suumo_images/20119720/20119720_6398008e5686c90...,2d89baa59bb99f6daec20b5dfa46528af2d336e4461bad...
2,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,https://img01.suumo.com/jj/resizeImage?src=gaz...,kitchen,suumo_images/20119720/20119720_f2528688dc1578b...,29a8c640a0a9070cc6bed44ee0e3067977e333fa526fa0...
3,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,https://img01.suumo.com/jj/resizeImage?src=gaz...,bathroom,suumo_images/20119720/20119720_d7ec3a9539d0e32...,0122d9cf525d4110b38a3c8c6aa29635025509ee303248...
4,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,https://img01.suumo.com/jj/resizeImage?src=gaz...,washroom,suumo_images/20119720/20119720_f754dfbc224f360...,cade908136d50b855975551a829543d06c94a8d8711577...
...,...,...,...,...,...,...,...
2487,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,interior,suumo_images/20344616/20344616_ee438bbfde1df84...,5d9682b83e74a6dded0aad99cb550ce00dd8916fde3fd3...
2488,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,storage,suumo_images/20344616/20344616_c1fb846f99142f2...,f0da48381d7d79881dddaa9e3129fb3b5f406f7e7cd319...
2489,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,entrance,suumo_images/20344616/20344616_c32122460e229e6...,b263eff73b58e19f464a4cdf5d0d9d704a8cfebb2d02f2...
2490,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,entrance,suumo_images/20344616/20344616_b018d9a12880488...,92ec671b9a807ab4ce20eb17bc9ba72c2bba6d9c1f6a4b...
2491,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,living,suumo_images/20344616/20344616_343f23d8f7aa88e...,77856969ed9f634897b7472ae9462857bb3635c493e278...

In [ ]:
#keep only the listings that have 5 or more images
listings_keep = listing_data[listing_data['interior_image_count'] >= 5]
listings_keep

,source,source_id,url,price_man_yen,layout,area_sqm,year_built,floor_number,floors_total,address,nearest_station,walk_minutes,interior_image_count
1,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,3799,3LDK,NaN,2000,3,6,千葉県市川市広尾１-10-10,南行徳駅,17.0,13
2,suumo,20143796,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,3799,3LDK,NaN,2000,3,6,千葉県市川市広尾１,南行徳駅,17.0,14
3,suumo,78933829,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,2688,4LDK,NaN,1974,4,5,千葉県市川市高谷２-7-7,原木中山駅,8.0,13
5,suumo,79221868,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,5298,3LDK,NaN,2006,8,20,千葉県市川市島尻,浦安駅,18.0,12
6,suumo,20037257,https://suumo.jp/ms/chuko/chiba/sc_matsudo/nc_...,2780,3LDK,NaN,1988,13,13,千葉県松戸市新松戸３,新松戸駅,4.0,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,suumo,20340216,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,2400,3LDK,NaN,1991,7,10,東京都足立区小台１,足立小台駅,8.0,12
97,suumo,20340904,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,4380,2LDK,NaN,1985,7,8,東京都足立区東和５,北綾瀬駅,9.0,26
98,suumo,20341785,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,3980,3LDK,NaN,1982,11,12,東京都足立区梅田７,梅島駅,6.0,40
99,suumo,20344541,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,2680,1DK,NaN,1989,2,3,東京都足立区綾瀬６,綾瀬駅,14.0,38
100,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,2380,2LDK,NaN,1974,3,8,東京都足立区梅田７-22-9,梅島駅,7.0,39

In [15]:
#remove the images of listings not being used
images_relevant = images_data[images_data['source_id'].isin(listings_keep['source_id'])]
images_relevant

,source,source_id,listing_url,image_url,image_tag,image_path,image_sha256
0,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,https://img01.suumo.com/jj/resizeImage?src=gaz...,kitchen,suumo_images/20119720/20119720_df8db223a09d1f4...,c93f3b913205421242f7dac495beb62842929f3ae6f22c...
1,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,https://img01.suumo.com/jj/resizeImage?src=gaz...,kitchen,suumo_images/20119720/20119720_6398008e5686c90...,2d89baa59bb99f6daec20b5dfa46528af2d336e4461bad...
2,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,https://img01.suumo.com/jj/resizeImage?src=gaz...,kitchen,suumo_images/20119720/20119720_f2528688dc1578b...,29a8c640a0a9070cc6bed44ee0e3067977e333fa526fa0...
3,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,https://img01.suumo.com/jj/resizeImage?src=gaz...,bathroom,suumo_images/20119720/20119720_d7ec3a9539d0e32...,0122d9cf525d4110b38a3c8c6aa29635025509ee303248...
4,suumo,20119720,https://suumo.jp/ms/chuko/chiba/sc_ichikawa/nc...,https://img01.suumo.com/jj/resizeImage?src=gaz...,washroom,suumo_images/20119720/20119720_f754dfbc224f360...,cade908136d50b855975551a829543d06c94a8d8711577...
...,...,...,...,...,...,...,...
2487,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,interior,suumo_images/20344616/20344616_ee438bbfde1df84...,5d9682b83e74a6dded0aad99cb550ce00dd8916fde3fd3...
2488,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,storage,suumo_images/20344616/20344616_c1fb846f99142f2...,f0da48381d7d79881dddaa9e3129fb3b5f406f7e7cd319...
2489,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,entrance,suumo_images/20344616/20344616_c32122460e229e6...,b263eff73b58e19f464a4cdf5d0d9d704a8cfebb2d02f2...
2490,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,entrance,suumo_images/20344616/20344616_b018d9a12880488...,92ec671b9a807ab4ce20eb17bc9ba72c2bba6d9c1f6a4b...
2491,suumo,20344616,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,living,suumo_images/20344616/20344616_343f23d8f7aa88e...,77856969ed9f634897b7472ae9462857bb3635c493e278...

In [19]:
images_relevant['image_tag'].value_counts()

image_tag
living        726
other_room    421
kitchen       407
bathroom      222
washroom      194
toilet        171
entrance      160
storage       121
interior       37
room           11
closet          4
dining          1
bedroom         1
Name: count, dtype: int64

## delete folders from suumo_images that are no longer needed

In [22]:
ids_to_delete = listing_data[listing_data['interior_image_count'] < 5]['source_id']
len(ids_to_delete)

14

In [ ]:
def delete_folder_by_name(source_id):
    """
    Deletes a folder and all its contents recursively.

    Args:
        folder_path (str or path-like object): The path to the folder to be deleted.
    """
    source_id = 0000
    folder_path = f'raw_data/suumo_images/{source_id}'
    if os.path.isdir(folder_path):
        try:
            # Recursively remove the directory and all its contents
            shutil.rmtree(folder_path)
            print(f"Directory '{folder_path}' has been removed successfully.")
        except OSError as e:
            print(f"Error: {folder_path} : {e.strerror}")
    else:
        print(f"Error: Directory '{folder_path}' not found or is not a directory.")