In [121]:
from sklearn.metrics import log_loss, accuracy_score
import pandas as pd
import json

In [103]:
df = pd.read_csv('assessment_output.csv', sep=";")
df.head()

,source_id,listing_url,image_url,RoomType,Luxury,Brightness,Condition,image_name,image_path,default_image,room_type,scoring_dict
0,20277732,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,living room,yes,yes,new,20277732_eaa711a75a.jpg,raw_data/suumo_images/20277732/20277732_eaa711...,1,kitchen,"{'luxury': 0.37890625, 'brightness': 0.2695312..."
1,20277732,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,living room,yes,yes,new,20277732_7c57695877.jpg,raw_data/suumo_images/20277732/20277732_7c5769...,1,floor plan,"{'luxury': -1000, 'brightness': -1000, 'condit..."
2,20277732,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,living room,yes,yes,new,20277732_274be42c2b.jpg,raw_data/suumo_images/20277732/20277732_274be4...,1,bathroom,"{'luxury': 0.37890625, 'brightness': 0.2226562..."
3,20277732,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,kitchen,yes,yes,new,20277732_c35b746f90.jpg,raw_data/suumo_images/20277732/20277732_c35b74...,1,kitchen,"{'luxury': 0.4375, 'brightness': 0.18359375, '..."
4,20277732,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,bedroom,no,yes,old,20277732_bbd7ffee05.jpg,raw_data/suumo_images/20277732/20277732_bbd7ff...,1,bathroom,"{'luxury': 0.53125, 'brightness': 0.1328125, '..."

In [104]:
df = df.drop(columns=['listing_url', 'image_url', "image_name", 'default_image'])
df.head()

,source_id,RoomType,Luxury,Brightness,Condition,image_path,room_type,scoring_dict
0,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_eaa711...,kitchen,"{'luxury': 0.37890625, 'brightness': 0.2695312..."
1,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_7c5769...,floor plan,"{'luxury': -1000, 'brightness': -1000, 'condit..."
2,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_274be4...,bathroom,"{'luxury': 0.37890625, 'brightness': 0.2226562..."
3,20277732,kitchen,yes,yes,new,raw_data/suumo_images/20277732/20277732_c35b74...,kitchen,"{'luxury': 0.4375, 'brightness': 0.18359375, '..."
4,20277732,bedroom,no,yes,old,raw_data/suumo_images/20277732/20277732_bbd7ff...,bathroom,"{'luxury': 0.53125, 'brightness': 0.1328125, '..."

In [132]:
json_string = df["scoring_dict"]
scoring_dict = pd.json_normalize(json_string.apply(eval))
df["score_lux"] = scoring_dict["luxury"]
df["score_bright"]= scoring_dict["brightness"]
df["score_cond"]= scoring_dict["condition"]
df.head()

,source_id,RoomType,Luxury,Brightness,Condition,image_path,room_type,scoring_dict,score_lux,score_bright,score_cond
0,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_eaa711...,kitchen,"{'luxury': 0.37890625, 'brightness': 0.2695312...",0.378906,0.269531,0.56250
1,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_7c5769...,floor plan,"{'luxury': -1000, 'brightness': -1000, 'condit...",-1000.000000,-1000.000000,-1000.00000
2,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_274be4...,bathroom,"{'luxury': 0.37890625, 'brightness': 0.2226562...",0.378906,0.222656,0.43750
3,20277732,kitchen,yes,yes,new,raw_data/suumo_images/20277732/20277732_c35b74...,kitchen,"{'luxury': 0.4375, 'brightness': 0.18359375, '...",0.437500,0.183594,0.50000
4,20277732,bedroom,no,yes,old,raw_data/suumo_images/20277732/20277732_bbd7ff...,bathroom,"{'luxury': 0.53125, 'brightness': 0.1328125, '...",0.531250,0.132812,0.46875

In [117]:
keep_rows = df["room_type"] != "floor plan"
df_cleaned = df[keep_rows]
df_cleaned.head()

,source_id,RoomType,Luxury,Brightness,Condition,image_path,room_type,scoring_dict,score_lux,score_bright,score_cond
0,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_eaa711...,kitchen,"{'luxury': 0.37890625, 'brightness': 0.2695312...",0.378906,0.269531,0.562500
2,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_274be4...,bathroom,"{'luxury': 0.37890625, 'brightness': 0.2226562...",0.378906,0.222656,0.437500
3,20277732,kitchen,yes,yes,new,raw_data/suumo_images/20277732/20277732_c35b74...,kitchen,"{'luxury': 0.4375, 'brightness': 0.18359375, '...",0.437500,0.183594,0.500000
4,20277732,bedroom,no,yes,old,raw_data/suumo_images/20277732/20277732_bbd7ff...,bathroom,"{'luxury': 0.53125, 'brightness': 0.1328125, '...",0.531250,0.132812,0.468750
5,20277732,bathroom,yes,yes,new,raw_data/suumo_images/20277732/20277732_8b8db6...,bathroom,"{'luxury': 0.62109375, 'brightness': 0.1640625...",0.621094,0.164062,0.292969

In [131]:
#log_loss
loss_lux = log_loss(df_cleaned["Luxury"] == "yes", df_cleaned["score_lux"])
loss_bright = log_loss(df_cleaned["Brightness"] == "yes", df_cleaned["score_bright"])
loss_cond = log_loss(df_cleaned["Condition"] == "new", df_cleaned["score_cond"])
loss_lux, loss_bright, loss_cond

(0.67718583463378, 0.9524724478853852, 0.7853922848822366)

In [130]:
#accuracy
lux_pred = df_cleaned["score_cond"] > 0.5
lux_actual = df_cleaned["Condition"] == "yes"
accuracy = accuracy_score(lux_pred, lux_actual)
accuracy

0.6779661016949152

In [ ]:
#df in batches