In [87]:
from sklearn.metrics import log_loss
import pandas as pd
import json

In [88]:
df = pd.read_csv('assessment_output.csv', sep=";")
df.head()

,source_id,listing_url,image_url,RoomType,Luxury,Brightness,Condition,image_name,image_path,default_image,room_type,scoring_dict
0,20277732,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,living room,yes,yes,new,20277732_eaa711a75a.jpg,raw_data/suumo_images/20277732/20277732_eaa711...,1,kitchen,"{'luxury': 0.37890625, 'brightness': 0.2695312..."
1,20277732,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,living room,yes,yes,new,20277732_7c57695877.jpg,raw_data/suumo_images/20277732/20277732_7c5769...,1,floor plan,"{'luxury': -1000, 'brightness': -1000, 'condit..."
2,20277732,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,living room,yes,yes,new,20277732_274be42c2b.jpg,raw_data/suumo_images/20277732/20277732_274be4...,1,bathroom,"{'luxury': 0.37890625, 'brightness': 0.2226562..."
3,20277732,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,kitchen,yes,yes,new,20277732_c35b746f90.jpg,raw_data/suumo_images/20277732/20277732_c35b74...,1,kitchen,"{'luxury': 0.4375, 'brightness': 0.18359375, '..."
4,20277732,https://suumo.jp/ms/chuko/tokyo/sc_adachi/nc_2...,https://suumo.jp/front/gazo/bukken/030/N010000...,bedroom,no,yes,old,20277732_bbd7ffee05.jpg,raw_data/suumo_images/20277732/20277732_bbd7ff...,1,bathroom,"{'luxury': 0.53125, 'brightness': 0.1328125, '..."

In [89]:
df = df.drop(columns=['listing_url', 'image_url', "image_name", 'default_image'])
df.head()

,source_id,RoomType,Luxury,Brightness,Condition,image_path,room_type,scoring_dict
0,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_eaa711...,kitchen,"{'luxury': 0.37890625, 'brightness': 0.2695312..."
1,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_7c5769...,floor plan,"{'luxury': -1000, 'brightness': -1000, 'condit..."
2,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_274be4...,bathroom,"{'luxury': 0.37890625, 'brightness': 0.2226562..."
3,20277732,kitchen,yes,yes,new,raw_data/suumo_images/20277732/20277732_c35b74...,kitchen,"{'luxury': 0.4375, 'brightness': 0.18359375, '..."
4,20277732,bedroom,no,yes,old,raw_data/suumo_images/20277732/20277732_bbd7ff...,bathroom,"{'luxury': 0.53125, 'brightness': 0.1328125, '..."

In [93]:
json_string = df["scoring_dict"][0]
scoring_dict = eval(json_string)
df["score_lux"] = scoring_dict["luxury"]
df["score_bright"]= scoring_dict["brightness"]
df["score_cond"]= scoring_dict["condition"]
df.head()

,source_id,RoomType,Luxury,Brightness,Condition,image_path,room_type,scoring_dict,score_lux,score_bright,score_cond
0,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_eaa711...,kitchen,"{'luxury': 0.37890625, 'brightness': 0.2695312...",0.378906,0.269531,0.5625
1,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_7c5769...,floor plan,"{'luxury': -1000, 'brightness': -1000, 'condit...",0.378906,0.269531,0.5625
2,20277732,living room,yes,yes,new,raw_data/suumo_images/20277732/20277732_274be4...,bathroom,"{'luxury': 0.37890625, 'brightness': 0.2226562...",0.378906,0.269531,0.5625
3,20277732,kitchen,yes,yes,new,raw_data/suumo_images/20277732/20277732_c35b74...,kitchen,"{'luxury': 0.4375, 'brightness': 0.18359375, '...",0.378906,0.269531,0.5625
4,20277732,bedroom,no,yes,old,raw_data/suumo_images/20277732/20277732_bbd7ff...,bathroom,"{'luxury': 0.53125, 'brightness': 0.1328125, '...",0.378906,0.269531,0.5625

In [ ]:
y_true = [0, 1]
y_pred = [[.9, .1], [.8, .2], [.3, .7], [.01, .99]]
log_loss(y_true, y_pred)
0.1738